### ISSUE TITLE
vkfw::PlatformError when running on wayland

### ISSUE THREAD

**Issue by cykrr** [Cvelth/vkfw#1] opened 2022-03-25 22:55 UTC
Hey, I'm trying to create a window with vkfw in a Wayland WM (Sway), and it doesn't work well. When i try to run it with glfwCreateWindow it works, and switching to glfw-x11 package variant as well (glfw-wayland is the one that doesn't work). Any help is appreciated.

Log is: 
`
vkfw::createWindow: A platform-specific error occurred that does not match any of the more specific categories`

**Comment by Cvelth** [comment] 2022-03-26 06:55
Hi! Thanks for showing interest in vkfw!

Could you please kindly try and run a simple test:
```
#include <iostream>

#define VKFW_NO_STRUCT_CONSTRUCTORS
#define VKFW_NO_EXCEPTIONS
#include "vkfw/vkfw.hpp"

void try_vkfw(std::ostream &log) {
  auto [initialization_error_code, instance] = vkfw::initUnique();
  log << "vkfw_initialization: " << vkfw::to_string(initialization_error_code) << '\n';

  log << "vulkan_support: " << (vkfw::vulkanSupported() ? "yes" : "no") << '\n';

  auto [window_error_code, window_handle] = vkfw::createWindowUnique(1280, 720, "vkfw", { .resizable = true });
  log << "vkfw_window_creation: " << vkfw::to_string(window_error_code) << '\n';

  while (vkfw::check(window_handle->shouldClose().result) && !window_handle->shouldClose().value) {
    auto waiting_error_code = vkfw::waitEvents();
    if (!vkfw::check(waiting_error_code)) {
      log << "vkfw_wait_events: " << vkfw::to_string(waiting_error_code) << '\n';
      auto closing_error_code = window_handle->setShouldClose(true);
      log << "vkfw_close_window: " << vkfw::to_string(closing_error_code) << '\n';
    }
  }

  log << std::endl;
}

void try_glfw(std::ostream &log) {
  auto initialization_successful = glfwInit();
  log << "glfw_initialization: " << (initialization_successful ? "yes" : "no") << '\n';

  char const *error_buffer;

  glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
  log << "glfw_window_hint: " << (glfwGetError(&error_buffer) ? error_buffer : "no error") << '\n';

  auto window_handle = glfwCreateWindow(1280, 720, "glfw", nullptr, nullptr);
  log << "glfw_window_creation: " << (glfwGetError(&error_buffer) ? error_buffer : "no error") << '\n';

  while (!glfwWindowShouldClose(window_handle)) {
    if (glfwGetError(&error_buffer)) {
      log << "glfw_should_close: " << (error_buffer ? error_buffer : "no error") << '\n';

      glfwSetWindowShouldClose(window_handle, true);
      log << "glfw_close_window: " << (glfwGetError(&error_buffer) ? error_buffer : "no error") << '\n';
    }

    glfwWaitEvents();
    if (glfwGetError(&error_buffer)) {
      log << "glfw_wait_events: " << (error_buffer ? error_buffer : "no error") << '\n';

      glfwSetWindowShouldClose(window_handle, true);
      log << "glfw_close_window: " << (glfwGetError(&error_buffer) ? error_buffer : "no error") << '\n';
    }
  }

  glfwDestroyWindow(window_handle);
  log << "glfw_destroy_window: " << (glfwGetError(&error_buffer) ? error_buffer : "no error") << '\n';

  glfwTerminate();

  log << std::endl;
}

int main() {
  try_vkfw(std::cout);
  try_glfw(std::cout);

  return 0;
}
```

What I'm looking for is whether there are any differences in behaviour between the two windows.

**Comment by cykrr** [comment] 2022-04-01 16:05
Hey, sorry for my late response and thank you for answering, when i run the code the following shows up 

```
$ g++ main.cpp  -I vkfw/include/ -lglfw
$ ./a.out
a.out: vkfw/include/vkfw/vkfw.hpp:1451: typename vkfw::ResultValueType<vk::UniqueHandle<Type, vk::DispatchLoaderStatic> >::type vkfw::createResultValueUnique(vkfw::Result, T&, const char*) [with T = vkfw::Instance; typename vkfw::ResultValueType<vk::UniqueHandle<Type, vk::DispatchLoaderStatic> >::type = vkfw::ResultValue<vk::UniqueHandle<vkfw::Instance, vk::DispatchLoaderStatic> >]: Assertion `result == Result::VKFW_ENUMERATOR(Success)' failed.

```
Regards.

**Comment by Cvelth** [comment] 2022-04-01 17:00
This specific assert seems to indicate that the call `glfwInit` returned a non-zero value.
Let's try and detect the specifics behind what problem it's encountering using a callback.

Could you please call `try_glfw` function from the previous listing like so:
```cpp
void logging_error_callback(int error_code, const char *description) {
  std::cout << "An error was encountered (" << error_code << "): " << description << '\n';
}

int main() {
  glfwSetErrorCallback(logging_error_callback);
  try_glfw(std::cout);

  return 0;
}
```

**Comment by cykrr** [comment] 2022-04-01 20:01
The following happens with glfw and vkfw respectively. Hope it helps
```
glfwSetErrorCallback(logging_error_callback);
try_glfw(std::cout);


glfw_initialization: yes
glfw_window_hint: no error
An error was encountered (65544):Wayland: Focusing a window requires user interaction
glfw_window_creation: Wayland: Focusing a window requires user interaction

glfwSetErrorCallback(logging_error_callback);
try_vkfw(std::cout);

vkfw_initialization: No error has occurred
vulkan_support: yes
An error was encountered (65544):Wayland: Focusing a window requires user interaction
a.out: vkfw/include/vkfw/vkfw.hpp:1451: typename vkfw::ResultValueType<vk::UniqueHandle<Type, vk::DispatchLoaderStatic> >::type vkfw::createResultValueUnique(vkfw::Result, T&, const char*) [with T = vkfw::Window; typename vkfw::ResultValueType<vk::UniqueHandle<Type, vk::DispatchLoaderStatic> >::type = vkfw::ResultValue<vk::UniqueHandle<vkfw::Window, vk::DispatchLoaderStatic> >]: Assertion `result == Result::VKFW_ENUMERATOR(Success)' failed.```

**Comment by Cvelth** [comment] 2022-04-01 20:37
Good news is that it seems to be a known error plaguing a bunch of GLFW wrappers.
You can read in more details in this issue: https://github.com/glfw/glfw/issues/1121

Bad news is that there's no "clean" fix. At least not for the release GLFW version (3.3).
The problem is that Wayland offers limited window focus functionality and GLFW tries to notify about that problem.
If you don't want to deal with using not-100%-stable-fork of the libraries, your best bet is to try and detect this error so that you can ignore it. The created should be usable despite this error.

If you're using the exception-flavoured vkfw, you can just wrap your `createWindow[Unique]` call into a `try { . . . } catch` block singling out the [platform error](https://github.com/Cvelth/vkfw/blob/ed25b204146ce4013597706ccce3e72f49ae3462/include/vkfw/vkfw.hpp#L1333) exception so you can ignore it.

For exceptionless vkfw you can try and provide your own "assert" before including the header like so:
```cpp
#define IGNORE_AN_ERROR(condition) /* does nothing */
#define VKFW_ASSERT_ON_RESULT IGNORE_AN_ERROR
```
The downside is that this would force you to check your errors manually (but at least you can make sure that the error `createWindow` is reporting is the one you expect).

I hope this helps.

**Comment by cykrr** [comment] 2022-04-01 22:17
Yes man this definitely helps. I want to thank you for your time, for your support and for creating vkfw :).

**Comment by Cvelth** [comment] 2022-04-02 06:18
Feel free to close the issue if that's it for this question.

P. S. New issues (or even PRs if you find something vkfw is missing) are always welcome.

**Closed** 2022-04-03 05:26 UTC
